### ISSUE TITLE
Pip install doesn't install core XXP templates into site-packages

### ISSUE THREAD

**Issue by felixleong** [clearclaw/xxpaper#6]
**Issue**

After pip installing the xxpaper package and attempting to make the sample file: i.e. `xxpaper make 1830-Paper.xxp`, the command failed stating that it cannot find the default XXP templates.

```
CRITICAL:logtool.log_fault_impl:FAULT: /home/felix/.local/share/virtualenvs/xxpapersandbox-_3AFqu5s/local/lib/python2.7/site-packages/xxpaper/main.py(45): IOError('CfgStack: Cannot find/parse file for XXP_DEFAULT.xxp',)
```

**Steps to Reproduce**

1. `pipenv --python 2.7 install git+https://github.com/clearclaw/xxpaper#egg=xxpaper`
2. `pipenv run xxpaper make 1830-Paper.xxp`

**Reason of Failure**

Upon inspection, the pip install will not copy the XXP_*.xxp core template files into the package directory.

**Fix or Workaround**
Update the packaging config to copy the XXP_*.xxp files into the package directory.

As a workaround, it is also possible to copy the XXP_*.xxp into your local project directory.

**Comment by clearclaw** [comment]
We're coming up quickly on v1 release.  Thanks for catching this one -- it will be fixed.

**Comment by clearclaw** [comment]
Fixed in the release now pushed to the cheese shop.
